name: Deploy UserScript

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Busting (update version)
        run: |
          for script in $(git diff --name-only HEAD~1 HEAD | grep '\.user\.js$'); do
            sed -i "s/@version      [0-9.]*/@version      $(date +'%Y%m%d%H%M%S')/" $script
          done

      - name: Commit & Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add *.user.js
          git commit -m "Update version timestamp"
          git push
